version: '3.8'

services:
  host1:
    build:
      context: .
      args:
        ROOT_PASSWORD: ${ROOT_PASSWORD}
    container_name: target-host1
    hostname: target-host1
    ports:
      - "${HOST1_PORT}:22"
      - "${HOST1_NGINX_PORT}:80"
    networks:
      - awx-target-net

  host2:
    build:
      context: .
      args:
        ROOT_PASSWORD: ${ROOT_PASSWORD}
    container_name: target-host2
    hostname: target-host2
    ports:
      - "${HOST2_PORT}:22"
      - "${HOST2_NGINX_PORT}:80"
    networks:
      - awx-target-net

networks:
  awx-target-net:
    driver: bridge
