---
- name: Install NGINX dynamically based on OS
  hosts: all
  become: true
  tasks:
    - name: Gather OS facts
      ansible.builtin.setup:

    - name: Install NGINX on Ubuntu
      apt:
        update_cache: yes
        name: nginx
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install NGINX on RedHat-based systems
      yum:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Ensure NGINX is enabled and running
      service:
        name: nginx
        state: started
        enabled: yes